name: CI/CD Blue-Green

# Controla cuándo se ejecutará el flujo de trabajo
on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Integración Continua
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4 

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validar sintaxis de Python
        run: python -m py_compile app.py
            
      - name: Ejecutatr pruebas basicas
        run: |
          python -c "from app import crear_servidor; print('Codigo Valido')"
